- name: Create Prometheus system group
  group:
    name: "{{ prometheus_group }}"
    state: present

- name: Create Prometheus system user
  user:
    name: "{{ prometheus_user }}"
    shell: /bin/bash
    group: "{{ prometheus_group }}"
    state: present

- name: Create a {{ prometheus_db_dir }} if it does not exist
  file:
    path: {{ prometheus_db_dir }}
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: directory
    mode: '0755'

- name: Create a {{ prometheus_config_dir }}/ subdirectories if it does not exist
  file:
    path: "{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: directory
    mode: '0755'
  with_items:
    - {{ prometheus_config_dir }}/rules
    - {{ prometheus_config_dir }}/rules.d
    - {{ prometheus_config_dir }}/files_sd

- name: Create a {{ prometheus_config_dir }}/ if it does not exist
  file:
    path: {{ prometheus_config_dir }}/
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: directory
    mode: '0755'