- name: Create Prometheus system group
  group:
    name: "{{ prometheus_group }}"
    state: present

- name: Create Prometheus system user
  user:
    name: "{{ prometheus_user }}"
    shell: /bin/bash
    group: "{{ prometheus_group }}"
    state: present

- name: Create a /var/lib/prometheus if it does not exist
  file:
    path: /var/lib/prometheus
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: directory
    mode: '0755'

- name: Create a /etc/prometheus/ if it does not exist
  file:
    path: /var/lib/prometheus
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: directory
    mode: '0755'

- name: Create a /etc/prometheus/ subdirectories if it does not exist
  file:
    path: "{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: directory
    mode: '0755'
    with_items:
      - /var/lib/prometheus/rules
      - /var/lib/prometheus/rules.d
      - /var/lib/prometheus/files_sd