- hosts: localhost
  become: true
  roles:
  - role: prometheus-preconf
  - role: prometheus-download-files
  - role: prometheus-install
  - role: node-exporter
    when: "{{ prometheus_node_exporter_install  | default('yes') }} == 'yes'"