##############
# Prometheus #
##############

# Prometheus user
prometheus_user: prometheus
# Prometheus group
prometheus_group: prometheus
# Prometheus binaries directory
prometheus_binary_install_dir: '/usr/local/bin'
# Prometheus config directory
prometheus_config_dir: '/etc/prometheus'
# Prometheus database directory
prometheus_db_dir: '/var/lib/prometheus'
# Address on which prometheus will be listening
prometheus_web_listen_address: "0.0.0.0"
# Port on which prometheus will be listening
prometheus_port: 9090
# Prometheus URL package version to download
prometheus_download_url: https://github.com/prometheus/prometheus/releases/download/v2.28.0/prometheus-2.28.0.linux-amd64.tar.gz

#################
# Node Exporter #
#################

# Install Node Exporter | Default: "yes" | If missing or different than "yes", Node Exporter will not be installed
prometheus_node_exporter_install: yes
# Node exporter group
node_exporter_group: node_exporter
# Node exporter user
node_exporter_user: node_exporter
# Node exporter URL package version to download
node_exporter_download_url: https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz
# Node Exporter metrics directory | Here you can add custom metrics
node_exporter_metrics_dir: /prometheus/metrics
# Node Exporter binaries directory
node_exporter_binary_install_dir: '/usr/local/bin'
# Node Exporter scrape interval
node_exporter_scrape_interval: 5s
node_exporter_port: 9100
