- name: Install Prometheus
  copy:
    src: "/tmp/prometheus/{{ prometheus_unarchive_folder.files[0] }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  with_items:
      - prometheus
      - promtool

- name: Add Prometheus template
  template:
    src: "{{ role_path }}/templates/prometheus.yml"
    dest: /etc/prometheus/
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: Create Prometheus systemd service
  template:
    src: "{{ role_path }}/templates/prometheus.service"
    dest: /etc/systemd/system/

- name: Enable Prometheus systemd daemon and start service
  command: "{{ item }}"
  with_items:
    - systemctl daemon-reload
    - systemctl start prometheus
    - systemctl enable prometheus