- name: Install Prometheus binaries
  copy:
    src: "/tmp/prometheus/{{ prometheus_unarchive_folder.files[0] }}/{{ item }}"
    dest: "{{ prometheus_binary_install_dir }}/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
  with_items:
      - prometheus
      - promtool

- name: Add Prometheus template
  template:
    src: "{{ role_path }}/templates/prometheus.yml"
    dest: "{{ prometheus_config_dir }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644

- name: Create Prometheus systemd service
  template:
    src: "{{ role_path }}/templates/prometheus.service"
    dest: /etc/systemd/system/
    mode: 0644

- name: Reload daemon
  systemd:
    daemon_reload: yes

- name: Start Prometheus service
  service:
    name: prometheus
    state: started

- name: Enable Prometheus systemd daemon
  systemd:
    name: prometheus
    enabled: yes
    masked: no