- name: Create Node Exporter system group
  group:
    name: "{{ node_exporter_group }}"
    state: present

- name: Create Node Exporter system user
  user:
    name: "{{ node_exporter_user }}"
    shell: /bin/bash
    group: "{{ node_exporter_group }}"
    state: present

- name: Create a {{ node_exporter_metrics_dir }} if it does not exist
  file:
    path: "{{ node_exporter_metrics_dir }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    state: directory
    mode: '0755'