- name: Install Node Exporter binaries
  copy:
    src: "/tmp/node_exporter/{{ node_exporter_unarchive_folder.files[0] }}/{{ item }}"
    dest: "{{ node_exporter_binary_install_dir }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0755
  with_items:
      - node_exporter

- name: Create Node_exporter systemd service
  template:
    src: "{{ role_path }}/templates/node_exporter.service"
    dest: /etc/systemd/system/
    mode: 0644

- name: Reload daemon
  systemd:
    daemon_reload: yes

- name: Start Node Exporter service
  service:
    name: node-exporter
    state: started

- name: Enable Node Exporter systemd daemon
  systemd:
    name: node-exporter
    enabled: yes
    masked: no

- name: Add job to prometheus config
  blockinfile:
    path: "{{ prometheus_config_dir }}/prometheus.yml"
    insertafter: 'scrape_configs:'
    block: |2
        # Node exporter job
        - job_name: 'node_exporter'
          scrape_interval: {{ node_exporter_scrape_interval }}
          static_configs:
            - targets: ['localhost:{{ node_exporter_port }}']

- name: Restart Prometheus service
  service:
    name: prometheus
    state: restarted